<!-- MES STYLES -->

<?php
echo $this->headLink()->appendStylesheet($this->basePath().'/css/pikachoose/bottom.css');
echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.jcarousel.min.js');
echo  $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.pikachoose.min.js');
?>

<!-- les scripts des images dans examen morphologique   -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.js');?>

<?php echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.css');?>
<?php
echo $this->headScript()->appendFile($this->basePath().'/js/mesjs/accouchement/complementcons_accordeon_controle.js');

echo $this->headLink()->appendStylesheet($this->basePath().'/css/mescss/bloquerDate.css'); //DatePicker
echo $this->headScript()->appendFile($this->basePath().'/js/mesjs/bloquerDate.js'); //Pour bloquer certaines dates?>


<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/maternite/accouchement/styleAdmission.css');?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/mescss/bloquerDate.css'); //DatePicker;?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/maternite/accouchement/jsAdmissionTest.js');
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/maternite/accouchement/jsMaternite.js' );?>

<?php use  Maternite\View\Helpers\DateHelper;
$Control = new DateHelper();?>

<script type="text/javascript">
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

$('#plus_admission').toggle(true);
$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Admission Patiente </span></a></li>");
dep_admission1();
$('#admission_style').css({'font-weight':'bold','color':'white','font-size':'22px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenuDesInterfaces').fadeIn().css({'visibility':'visible'});
});
</script>






<!--************************************************************************************************************-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--************************************************************************************************************-->



<style>
#contenuDesInterfaces{ visibility: hidden; };
</style>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 35px;'><iS style='font-size: 25px;'>&curren;</iS> RECHERCHER LE PATIENT</div>
     
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
     
<div id="contenuDesInterfaces" >
     <div id="contenu" >
        <div style="margin-right: 45px; float:right; font-size: 15px; color: gray; margin-top:5px;"><a style="text-decoration: none; cursor:pointer;" href="javascript:ajouterMaman()" ><img src='../images_icons/aj.gif' title="ajouter" /><i style="font-family: Times New Roman; font-size: 15px; color: green;"> ajouter un patient</i></a></div>
		<table style='width:95%; margin-left: 10px; align:center' class="table table-bordered tab_list_mini" id="patient">
			<thead >
			    <tr >
				    <th id="idpatient_" style='width: 15%;'><input type="text" name="search_browser" value=" Numero_Dossier" class="search_init" /></th>
					<th id="nom_" style='width: 15%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="prenom_" style='width: 17%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="nom_" style='width: 7%;'><input type="text" name="search_browser" value=" Age" class="search_init" /></th>
				<!--  	<th id="nom_" style='width: 13%;'><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>-->
					<th id="adresse_" style='width: 25%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="effectuer_" style='width: 8%;'><input type="hidden" value="" class="" />Options</th>

				</tr>

			</thead>

			<tbody id="donnees" class="liste_patient">

	            <?php /* AFFICHAGE DE LA LISTE DES PATIENTS */?>

			</tbody>

		</table>

<script type="text/javascript">
initialisation();
</script>
</div>

<!-- POP UP pour Confirmation Suppression -->
                            <div id="confirmation" title="Informations" style="display:none;">
                              <div id="info" style="font-size: 16px;">

                              </div>
                            </div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->





    <div id="declarer_deces">
          <a href="" id="precedent" style="text-decoration: none; font-family: police2; width:50px; margin-left:30px;">
	        <img style=" display: inline; " src='<?php echo $this->basePath().'/images_icons/transfert_gauche.PNG'?>' alt='Constantes' title="Rechercher" />
		    Pr&eacute;c&eacute;dent
		  </a>

		  <div id="info_patient">
		  </div>

		  <?php $today = new \DateTime('now');
		  $date = $today->format ( 'd/m/Y H:i' );?>
		  <div id="titre_info_deces">Admission    <div style='float:right; margin-right:15px; font-size:14px;'> Saint-Louis le, <?php echo $date;?></div></div>
		  <div id="barre_separateur">
		  </div>

		  <?php $form = $this->form ;
		        $form->setAttribute ( 'action', $this->url ( 'accouchement', array ('action' => 'enregistrer-admission') ) );
		        $form->setAttribute ( 'id' , 'formulairePrincipal');
		        $form->prepare();
		        echo $this->form()->openTag($form);
		       ?>
		  <?php echo $this->formhidden($form->get('id_patient')); ?>    
		   <?php //echo $this-> $this->formHidden($form->get('id_admission'));?>
		    <?php //echo $this-> $this->formHidden($form->get('id_grossesse'));?>
		  <div id="info_bebe" style='width: 100%; margin-top:10px; height:600px;'>
		  
               <div style="float:left; width:20%; height:10%;">
		       </div>
		       
		     
		       <div  style='width: 77%; float:left;'>
		        
		         <table id="form_patient" style="width:100%;">
		              
		       <div  style='font-family: police2;  height: 30px; padding-top: 16px; border-radius: unset;  background-color:#eeeeee; font-size: 17px; font-weight: bold;' >Antecedents </div> 
		                <tr>
	                         <td class="nombre" style='width: 33%;'><?php echo $this->formRow($form->get('enf_viv'));?></td>
		                 
		                       <td class="nombre" style='width: 33%;'><?php echo $this->formRow($form->get('geste'));?></td>
		                   <td class="nombre" style='width: 33%;'><?php echo $this->formRow($form->get('parite'));?></td>
		                             
		              </tr> 
		      
		                <tr>
		                  <td style='width: 33%;'>
                           <div class="comment-form-patient" ><label style='top: 5px;'>MORT-NE </label></div>
                           <div class="comment-form-patient_radio" ><?php echo $this->formRow($form->get('mort_ne'));?></div>
		                 </td>
		                  <td style='width: 33%;'>
		                   <div class="comment-form-patient" ><label style='top: 5px;'>CESAR</label></div> 
		                   <div class="comment-form-patient_radio" ><?php echo $this->formRow($form->get('cesar'));?></div>
		                 </td>
		                    <td style='width: 33%;'>
		                   <div class="comment-form-patient" ><label style='top: 5px;'>DYSTOCIE</label></div> 
		                   <div class="comment-form-patient_radio" ><?php echo $this->formRow($form->get('dystocie'));?></div>
		                 </td>
		                  <td >
		                   <div class="comment-form-patient" ><label style='top: 5px;'>ECLAMPSIE</label></div> 
		                   <div class="comment-form-patient_radio" ><?php echo $this->formRow($form->get('eclampsie'));?></div>
		              </td>
		              </tr>
		             
		          
		              </table>
		              <br />
		              <table id="form_patient" style="width:100%;">
		           	       <div style='font-family: police2;  height: 30px; padding-top: 16px; border-radius: unset;  background-color:#eeeeee; font-size: 17px; font-weight: bold;'> Grossesse </div>
		              <tr  class="comment-form-patient">
		                <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('ddr'));?></td>
		                <td class="comment-form-author" style='width: 37%; /*25px;'><?php echo $this->formRow($form->get('duree_grossesse'));?></td>
		                 <td style="width: 33%; height:50px;" >
		                   <div id= "BUcheckbox" style= 'width:35%; /*25px;'><label id="bb_attend" style=" margin-right: 11%; height: 30px; font-family: time new romans; font-size:18px;">
		                   Bb attendu
		                   </label></div> 
		                   <div class="comment-form-author" ><?php echo $this->formRow($form->get('bb_attendu'));?></div>
		              </td >
		             		 <td class="BbAttendu comment-form-author" style='width: 33%;'><?php echo $this->formRow($form->get('nombre_bb'));?></td>
		              </tr>
		              <tr>
		                <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('vat_1'));?></td>
		                <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('vat_2'));?></td>
		                <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('vat_3'));?></td>
		                   
                     <td class="comment-form-patient" style='width: 33%;'><?php echo $this->formRow($form->get('nb_cpn'));?></td>

		              </tr>
		              </table>
		      
		      
		       <div style="float:left; width:5%;">
		       </div>
		       <script>
             
             /****** MASK DE SAISIE ********/
          	 maskSaisie();
            </script>
		  </div>

		  <div style='width: 90%; height: 60px;'>
		     
                  <div id="terminer_annuler">
                    <div class="block" id="thoughtbot">
                       <button name="annuler" id="annuler" style=" height:35px; ">Annuler</button>
                    </div>
                    
                    <div class="block termineradmission" id="thoughtbot">
                       <button id="termineradmission" style=" height:35px; ">Terminer</button>
                    </div>
                  </div>
                </div>
                <div style='width: 40%;'></div>
          </div>
          <?php echo $this->form()->closeTag(); ?>
		  
    </div>
    
</div>

    

<div id="context-menu">
    <ul class="dropdown-menu" >
         <li><a style="cursor: pointer;" ><img id="visualiserCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='/simens/public/images_icons/voir2.png'>Visualiser</a></li>
         <li class="divider2"></li>
         <li><a style="cursor: pointer;"><img  id="suivantCTX" style='margin-right: 10px; width: 19px; height: 16px;' src='/simens/public/images_icons/transfert_droite.png'>Suivant</a></li>
         <li class="divider"></li>
         <li><a id="quitterCTX"  style="cursor: pointer;">Quitter</a></li>
    </ul>
</div>
		
		
<script>
animation();
$('#service').val("");
function ajouterMaman(){
	vart=tabUrl[0]+'public/accouchement/ajouter';
    $(location).attr("href",vart);
    return false;
}

</script>