<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/maternite/styleMaternite.css');?>

<!-- MES JS -->
<?php
echo $this->headScript ()->appendFile ( $this->basePath () . '/js/maternite/jsMaternite.js' );
echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/css/maternite/DatePicker.css' );
echo $this->headScript()->appendFile($this->basePath().'/js/maternite/accouchement/jsAjouter.js');
?>

<script>
//info_bulle();
//controle_saisie();

var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_dossier_patient').toggle(true);
$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Dossier Patiente </span></a></li>");
dep_dossier_patient1();
$('#nouveau_style').css({'font-weight':'bold','color':'white','font-size':'22px'});

$(window).load(function () {
	$('#wait').toggle(false);
	$('.contenu').fadeIn().css({'visibility':'visible'});
});

</script>

<style>
.contenu{ visibility: hidden };
</style>



<?php
$form = $this->form;
$form->setAttribute ( 'action', $this->url ( 'accouchement', array ('action' => 'enregistrement') ) );
$form->setAttribute ('enctype','multipart/form-data');
$this->form->prepare ();
echo $this->form ()->openTag ( $form );
?>

<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>


<div id="accordions" class="contenu">
     <div  id='depliant1' style='width: 140px; font-family: police2; color: green; font-size: 20px; font-weight: bold;'>Etat civil</div>
      <div style="max-height:300px;">

         <div class="photo_patient" id='photo'>
                  <input type='file' name="fichier" /> <!-- RECUPERER L'IMAGE -->
                  <!-- input type='hidden' id="fichier_tmp" name="fichier_tmp" /--> <!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
                 
         </div>
           
        <div style='width: 80%; float:left;'>
       
		<table id="form_patient" style="float: left;">

			<tr class="comment-form-patient">
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('SEXE'));?></td>
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('LIEU_NAISSANCE'));?></td>
                     <td style="width: 33%;"> <?php echo $this->formRow($this->form->get('EMAIL'));?></td>

                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('NOM'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('TELEPHONE'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('NATIONALITE_ORIGINE'));?></td>
                  </tr>

                  <tr class="comment-form-patient">
                     <td > <?php echo $this->formRow($this->form->get('PRENOM'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('PROFESSION'));?></td>
                     <td > <?php echo $this->formRow($this->form->get('NATIONALITE_ACTUELLE'));?></td>
                     
                  </tr>

                  <tr class="comment-form-patient">
                     <td style="width: 33%;"> 
                       <div class="age" style="float: left; width: 33%;"> <?php echo $this->formRow($this->form->get('AGE'));?> </div>
                       <div class="date_naiss" style="float: left; width: 60%;"> <?php echo $this->formRow($this->form->get('DATE_NAISSANCE'));?> </div>
                     </td >
                     <td > <?php echo $this->formRow($this->form->get('ADRESSE'));?></td>
                    
                     <td >  </td>
                  </tr>

		</table>
	  </div>
		
	  <div style='width: 3%; height: 150px; float:left;'>
		<div class="barre_vertical"></div>

		<div class="vider_formulaire" id="vider_champ">
			<hass> <input type="submit" title="Vider tout" name="vider"
				id="vider"> </hass>
		</div>

		<div class="supprimer_photo" id="div_supprimer_photo">
			<hass> <input name="supprimer_photo"> </hass>
			<!-- balise sans importance pour le moment -->
		</div>

		<div class="modifer_donnees" id="div_modifier_donnees">
			<hass> <input alt="modifer_donnees" title="modifer les donnees"
				name="modifer_donnees" id="modifer_donnees"> </hass>
		</div>
      </div>
      </div>

      <div id='depliant2' style='font-family: police2;  color: green; font-size: 20px; font-weight: bold;'>Compléments informations</div>
     <div style="max-height:100px;">
         
         <table id="form_patient" class="complement_medico-technique" style="width: 100%;">  
            <tr class="comment-form-patient">
              
                <td style="width: 25%;"> <?php echo $this->formRow($this->form->get('NOM_CONJOINT')); ?></td> 
                 <td style="width: 25%;"> <?php echo $this->formRow($this->form->get('PRENOM_CONJOINT')); ?></td> 
                  <td style="width: 25%;"> <?php echo $this->formRow($this->form->get('PROFESSION_CONJOINT')); ?></td> 
            </tr>
        </table>
                
                       
     </div>
	</div>
	
	<br />
	 <table style="width: 100%; ">
	  
	 <tr style="width: 100%;">
	  <td style="width: 42%;"></td>
	  <td style="width: 10%;" id="thoughtbot" >
		<button id="annuler"
			style="font-family: police2; font-size: 17px; font-weight: bold;">
			Annuler
		</button>
	  </td>
	  
	  <td style="width: 10%;" id="thoughtbot">
		<button type="submit" name="terminer" id="terminer"
			style=" font-family: police2; font-size: 17px; font-weight: bold;">
			Terminer
		</button>
	  </td>
	  <td style="width: 10%;" id="thoughtbot">
		<button type="submit" name="terminer_ad" id="terminer_ad"
			style=" font-family: police2; font-size: 17px; font-weight: bold;">
			Terminer et admettre
		</button>
	  </td>
	  <td style="width: 38%;"></td>
	  
	  </tr>
    </table>

<?php echo $this->form()->closeTag();
?>

<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression"
	style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img
			src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />

			Etes-vous s&ucirc;r de vouloir supprimer la photo ?
		</span>
	</p>
</div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->




<script> 


    $(document).keypress(function(e){
	if(e.keyCode == 13){
		e.preventDefault();
	}
    });
    $('#annuler').click(function(){ 
		 vart=tabUrl[0]+'public/accouchement';
	     $(location).attr("href",vart);
	     return false;
	});
</script>

